Introduction
# **Pandas**

 Q what is pandas ?

->pandas is a librery

->fast, powerful, flexible, and

->esy to use open source data analysis

->maniplulation tool , built on top of the python programing language.

Q.2 Type of Objects in pandas?

1.Series

2.DataFrame

#pandas Series
-> a pandas series is like coloum in a table (1D array holding a data of any type. )


->  a coloum is known a series in a table.

# Import Pandas

as we know pandas are dependent  or derived on numpy so
 import both  may be recommended

import pandas as pd

import numpy as np


#steps to import pandas

1 create a folder
2.create virtual enviroment  ---- >  at new terminal

  --> python -m venv name_of_virtual_enviroment -> write on terminal

3--> activate the virtual enviroment   --->write on terminal


 --->(name_of_virual_enviroment\scriptd\activate)

4 pip install pandas --> write on terminal


5.import  --> write code on screren

In [31]:

import numpy as np
print("imported")

import  pandas as pd
print ("impoerted pandas")

imported
impoerted pandas

#Series --> S capital hoga

#Series from Lists
# It has 2 thing
  1.Index

  2.Values

In [3]:
#String -- string se series bana skte h
country = ['india', 'pakistan','USA','Nepal','Srilanka']

pd.Series(country)   # S is caital on Series

0       india
1    pakistan
2         USA
dtype: object

In [5]:
#integers -- integer se series bana sakte h
runs = [13,24,56,76,100]
pd.Series(runs)   # S is caital on Series

0     13
1     24
2     56
3     76
4    100
dtype: int64

In [10]:
#custom index --khud k hisab se index bana sakte ho
marks = [ 67,57,90,100]
subjects =["maths", "english","hindi", "science"]
pd.Series( marks, index=subjects )

maths       67
english     57
hindi       90
science    100
dtype: int64

In [11]:
# setting a name --. to give name to your data
pd.Series( marks, index=subjects , name = "nitish k marks")

maths       67
english     57
hindi       90
science    100
Name: nitish k marks, dtype: int64

In [14]:
#store -- now store this in
marks = pd.Series( marks, index=subjects , name = "nitish k marks")
marks   #print krne ki need ni h simply typ marks

maths       67
english     57
hindi       90
science    100
Name: nitish k marks, dtype: int64

#Series from dict.
sreies ko hum list se bhi sakte h

series ko dict. se bhi  bana sakte h

In [17]:
marks = {
    "maths" :65,
    "english" : 67,
    "science" : 87,
    "hindi" :56
}

marks_series = pd.Series(marks,name= "nitish k marks")
marks_series

maths      65
english    67
science    87
hindi      56
Name: nitish k marks, dtype: int64

Series Attributes

In [19]:
#Size --> tells the size of the series
marks_series.size

4

In [21]:
#dtype  --> tells the  series dtype
marks_series.dtype

dtype('int64')

In [22]:
#name  --> tells the series name
marks_series.name

'nitish k marks'

In [25]:
#is unique --> tells allseries item are unique or not
marks_series.is_unique  --> #writtern true

#if we create new series
pd.Series([1,1,1,2,3,5,5]).is_unique

False

In [26]:
#index --> tels the all index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [27]:
#value -->store value at index
marks_series.values

array([65, 67, 87, 56])

Series using read_csv

In [49]:
#with one col
pd.read_csv('/content/subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [57]:
#Note - By default file jo read hoti hoti h type DataFrame h na ki series
type (pd.read_csv('/content/subs.csv',))

pandas.core.frame.DataFrame

In [60]:
#DataFrame ----> Series--> we use -- squeeze=true
subs = pd.read_csv('/content/subs.csv',squeeze=True)
subs

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

#series Method